# Generated by Django 3.2.16 on 2025-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250425_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Введите название ингредиента', max_length=100, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
